---
title: "tables"
author: "upulcooray"
date: "2021-06-22"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

This analysis was conducted to assess different opinions regarding the introduction of RFID (denture identification system)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(labelled)
library(gtsummary)
library(flextable)

# import data

load("data/isudata.RData")


```

```{r include=FALSE}

data <- df %>%  mutate(Speciality= case_when(Speciality== "forensic odontologist"~ "Forensic odontologists/ Carer",
                                             Speciality== "Carer"~ "Forensic odontologists/ Carer",
                                             TRUE~ "Other related proffession") %>% as.factor(),
                       
                       `Widely introduce RFID`= if_else(`Introduce RFID`== "Widely introduce","Agree","Not agree") %>% as_factor(),
                       `Against RFID`= if_else(`Introduce RFID`== "Aginst RFID","Against", "Not against") %>% as_factor()) 

```

<!-- ==============================Define table function====================== -->

```{r tab-fun, include=FALSE}

 
tab.fun <- function(staff="",headvar, full= FALSE) {
  
  
  
  if (full) {
    data.den <- data %>% select(headvar, `Widely introduce RFID`, `Against RFID` ) 
    staff <- "all participants"
  } 
  
  else {
    data.den <-      data %>% filter(`Staff type`== staff) %>% 
      select(headvar, `Widely introduce RFID`, `Against RFID` )  
    staff <- paste(staff,"staff")
  } 
  
    
  
  header <- data.den %>% select(all_of(headvar)) %>% colnames()
  
  title <- paste("Opinion on RFID introduction among",tolower(staff), "based on",tolower(header))
  
 tbl_summary(data.den,by= headvar)  %>%  
    
    add_p() %>% 
    modify_caption(caption = title) %>% 
    modify_spanning_header(c("stat_1", "stat_2") ~ header) %>% 
    bold_labels() %>% 
    as_flex_table()
  
}


```

#### *Difference in opinion among professionals based on work experience*

```{r    message=FALSE}

tab.fun("Dental","Work experience")
tab.fun("Nursing","Work experience")

```

#### *Difference in opinion based on the years of experience*

```{r    message=FALSE}

test <- tab.fun("Dental","Speciality") %>%  compose( j = "stat_1",
               value = as_paragraph(
                 "Forensic odontologists",
                 as_chunk(count(data$Speciality))
               ),
               part = "header")
  
  
  
  set_header_labels(
  values = list(stat_1 = "Forensic odontologists, N= 
                {n}"))

tab.fun("Dental","Speciality")
```

#### *Difference in opinion based on the specialty*

```{}
```
